from .practice_sample_1 import *

assert(exchange_numbers(30,40)==(40,30))
assert(isPositive(9)==True)
assert(checkDivisor(20,4)==[4,8,12,16,20])
assert(Divide(40,5)==(8,0))
assert(oddNumbers(15)==[1,3,5,7,9,11,13,15])
assert(sumOfDegits(143)==8)
assert(findSmallestDivisor(35)==5)
assert(sumOfSeries(1,3)==123)
assert(reverse(143)==341)
assert(average([1,3,5,7,9])==5)
assert(count(12345)==5)
assert(palindrome(1234321)==True)
assert(ifSubStringFound("Nit bit Sit Nit Kit Nit","Nit")==3)
assert(indexSubStringFound("Nit bit Sit Nit Kit Nit","Nit")==0)
assert(checkForCharacters("My")==True)
assert(replace("anna de armas")=="$nn$ de $rm$s")
assert(countVowels("aeiou")==5)
assert(replaceBlankSpace("I am Spiderman")=="I-am-Spiderman")
assert(findLength("nitin")==5)
assert(findLargerString("Nitin","Nithin")=="Nithin")
assert(countOfUpperLower("Anna De Armas")==(3,8))
assert(countCharsDigits("Ass98")==(3,2))
assert(fullPattern("Spiderman is an avenger","Spiderman")==True)
assert(cumulative_Sum([1,2,4,5,7])==[1,3,7,12,19])
print(tenRandomNumbers())
print(tenRandomNumbersRange())
print(uniqueRandomNumbers())
print(randomNumbers())